ALTER TABLE fonderie_plans
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS tier        INT  NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS features    JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS limits      JSONB NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS metadata    JSONB NOT NULL DEFAULT '{}';
